apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-balancer
  template:
    metadata:
      labels:
        app: load-balancer
    spec:
      containers:
      - name: load-balancer
        image: 1vancn/golb:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SERVICE_REGISTRY_URL
          value: http://service-discovery:3000/services
