version: "3"

services:
  go-gin-api:
    build: src/
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=pass
      - DB_NAME=mydb
      - SERVICE_HOST=service-discovery
    depends_on:
      - db
      - service-discovery
    networks:
      - api
  service-discovery:
    build: serviceDiscovery/
    networks:
      - api
  load-balancer:
    build: loadBalancer/
    ports:
      - "8080:8080"
    environment:
      - SERVICE_REGISTRY_URL=http://service-discovery:3000/services
    depends_on:
      - service-discovery
    networks:
      - api
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    networks:
      - api
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/init-db.sql

networks:
  api:
    driver: bridge
