version: "3"

services:
  go-gin-api:
    build: src/
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=pass
      - DB_NAME=mydb
    depends_on:
      - db
    networks:
      - api

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    networks:
      - api
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/init-db.sql

networks:
  api:
    driver: bridge
