apiVersion: v1
kind: Service
metadata:
  name: {{  .Values.global.servicediscovery.name  }}
spec:
  clusterIP: None
  selector:
    app: {{  .Values.global.servicediscovery.name  }}
  ports:
  - port: 3000
    targetPort: 3000
