apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Values.global.frontend.name  }}
spec:
  replicas: {{  .Values.replicasCount  }}
  selector:
    matchLabels:
      app: {{  .Values.global.frontend.name  }}
  template:
    metadata:
      labels:
        app: {{  .Values.global.frontend.name  }}
    spec:
      containers:
      - name: {{  .Values.global.frontend.name  }}
        image: {{  .Values.image.repository  }}:{{  .Values.image.tag  }}
        imagePullPolicy: {{  .Values.image.imagePullPolicy  }}
        ports:
        - containerPort: 5000
        env:
        - name: API_HOST
          value: {{  .Values.global.load-balancer.name  }}
        - name: API_PORT
          value: "8080"
        - name: API_URL
          value: http://load-balancer:8080
