apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{  .Values.global.go-gin-api.name  }}
spec:
  serviceName: {{  .Values.global.go-gin-api-headless.name  }}
  replicas: {{  .Values.replicaCount  }}
  selector:
    matchLabels:
      app: {{  .Values.global.go-gin-api.name  }}
  template:
    metadata:
      labels:
        app: {{  .Values.global.go-gin-api.name  }}
    spec:
      containers:
      - name: {{  .Values.global.go-gin-api.name  }}
        image: {{  .Values.image.repository  }}:{{  .Values.image.tag  }}
        imagePullPolicy: {{  .Values.image.imagePullPolicy  }}
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: {{  .Values.global.postgres.name  }}
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: {{  .Values.global.postgres.name  }}
        - name: DB_PASSWORD
          value: pass
        - name: DB_NAME
          value: mydb
        - name: DB_SSLMODE
          value: disable
        - name: SERVICE_HOST
          value: {{  .Values.global.service-discovery.name  }}
        - name: HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: HOST_FULL_NAME
          value: {{  .Values.global.go-gin-api-headless.name  }}.default.svc.cluster.local

