apiVersion: v1
kind: Service
metadata:
  name: {{  .Values.global.go-gin-api-headless.name  }}
spec:
  clusterIP: None
  selector:
    app: {{  .Values.global.go-gin-api.name  }}
  ports:
    - port: 8080
      targetPort: 8080
