apiVersion: v1
kind: Service
metadata:
  name: {{  .Values.global.goginapiheadless.name  }}
spec:
  clusterIP: None
  selector:
    app: {{  .Values.global.goginapi.name  }}
  ports:
    - port: 8080
      targetPort: 8080
