apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Values.global.loadbalancer.name  }}
spec:
  replicas: {{  .Values.replicasCount  }}
  selector:
    matchLabels:
      app: {{  .Values.global.loadbalancer.name  }}
  template:
    metadata:
      labels:
        app: {{  .Values.global.loadbalancer.name  }}
    spec:
      containers:
      - name: {{  .Values.global.loadbalancer.name  }}
        image: {{  .Values.image.repository  }}:{{  .Values.image.tag  }}
        imagePullPolicy: {{  .Values.image.imagePullPolicy  }}
        ports:
        - containerPort: 8080
        env:
        - name: SERVICE_REGISTRY_URL
          value: http://service-discovery:3000/services
