apiVersion: v1
kind: Service
metadata:
  name: {{  .Values.global.load-balancer.name  }}
spec:
  type: NodePort
  selector:
    app: {{  .Values.global.load-balancer.name  }}
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
